// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProbeAufgabeAPI.Data;

#nullable disable

namespace ProbeAufgabeAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240217143500_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProbeAufgabeAPI.DeviceInformation", b =>
                {
                    b.Property<int?>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Uid"));

                    b.Property<bool?>("AdvancedEnvironmentalConditions")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Failsafe")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InsertInto19InchCabinet")
                        .HasColumnType("bit");

                    b.Property<string>("InstallationPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MotionEnable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SimaticCatalog")
                        .HasColumnType("bit");

                    b.Property<bool?>("SiplusCatalog")
                        .HasColumnType("bit");

                    b.Property<int?>("TempMax")
                        .HasColumnType("int");

                    b.Property<int?>("TempMin")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.ToTable("DeviceInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
